### ISSUE TITLE
Ý tưởng businuess và phương pháp kỹ thuật - Cách tính độ khó từ vựng trong bản tin

### ISSUE THREAD

**Issue by baosws** [nmcntt2-cntn2016/project1-new-team#6]
"Theo trình độ: Hệ thống sẽ có một danh sách hầu hết các từ vựng tiếng anh, được phân theo cấp độ khó, từ 1 đến 10. Sau đó, thuật toán đánh giá sẽ duyệt hết các từ trong bản tin đó, thống kê số lượng từ vựng ở mỗi cấp độ, từ đó cho điểm đánh giá độ khó từ vựng của bản tin đó, từ 1 đến 10."

Cho điểm như thế nào? Tính expected value hay sao? (Cần cụ thể hơn)

**Comment by qcuong98** [comment]
Ta có thể xây dựng cơ sở dữ liệu để quản lý số từ xuất hiện ở tất cả các bài viết. Từ nào xuất hiện càng nhiều thì độ khó càng thấp. 
Ví dụ: nếu từ đó nằm ở 25% từ xuất hiện ít nhất thì sẽ có độ khó là 7.5
p/s: Không nhất thiết phải là thang điểm từ 1 đến 10.
